services:
  beam:
    image: beam-local
    build:
      context: beam
    command: beam --host-key-file /root/.ssh/id_beam_ed25519 --host beam.ssh.camp --bind-addr 0.0.0.0:2222
    restart: unless-stopped
    env_file: .env
    volumes:
      - "/home/ksdme/.ssh/id_beam_ed25519:/root/.ssh/id_beam_ed25519:ro"
    ports:
      - "2223:2222"
